# Практическое задание №1 по теме "Основные понятия и структуры PyTorch".

In [1]:
import torch

### 1. Создайте случайный FloatTensor размера 3x4x5

In [2]:
a = torch.rand(3,4,5,)
print(a.dtype)
print(a.type())
a

torch.float32
torch.FloatTensor


tensor([[[0.7548, 0.0741, 0.8563, 0.3692, 0.5082],
         [0.1621, 0.8922, 0.7951, 0.3053, 0.2351],
         [0.2639, 0.7812, 0.6346, 0.0438, 0.0680],
         [0.1621, 0.0722, 0.1276, 0.0424, 0.1538]],

        [[0.5848, 0.5395, 0.2786, 0.4605, 0.0967],
         [0.0623, 0.0096, 0.1896, 0.1860, 0.1155],
         [0.5996, 0.6664, 0.6653, 0.7234, 0.7092],
         [0.5928, 0.6780, 0.1193, 0.2927, 0.7002]],

        [[0.1878, 0.4551, 0.3368, 0.8187, 0.6328],
         [0.6920, 0.0404, 0.0204, 0.1607, 0.1052],
         [0.7648, 0.3784, 0.8045, 0.0189, 0.9484],
         [0.5626, 0.2203, 0.6875, 0.9488, 0.5734]]])

### 2. Выведите его форму (shape)

In [3]:
a.shape

torch.Size([3, 4, 5])

In [4]:
a.size()

torch.Size([3, 4, 5])

### 3. Приведите его к форме 6х10

In [5]:
a = a.reshape(6, 10)
print(a.shape)
a

torch.Size([6, 10])


tensor([[0.7548, 0.0741, 0.8563, 0.3692, 0.5082, 0.1621, 0.8922, 0.7951, 0.3053,
         0.2351],
        [0.2639, 0.7812, 0.6346, 0.0438, 0.0680, 0.1621, 0.0722, 0.1276, 0.0424,
         0.1538],
        [0.5848, 0.5395, 0.2786, 0.4605, 0.0967, 0.0623, 0.0096, 0.1896, 0.1860,
         0.1155],
        [0.5996, 0.6664, 0.6653, 0.7234, 0.7092, 0.5928, 0.6780, 0.1193, 0.2927,
         0.7002],
        [0.1878, 0.4551, 0.3368, 0.8187, 0.6328, 0.6920, 0.0404, 0.0204, 0.1607,
         0.1052],
        [0.7648, 0.3784, 0.8045, 0.0189, 0.9484, 0.5626, 0.2203, 0.6875, 0.9488,
         0.5734]])

### 4. Создайте случайный IntTensor размера 10

In [6]:
b = torch.randint(1, 10, size=(10,))
print(b.shape)
b

torch.Size([10])


tensor([9, 6, 9, 9, 9, 6, 5, 7, 6, 2])

### 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [7]:
c = a.mul(b)
print(c.shape)
c

torch.Size([6, 10])


tensor([[6.7928, 0.4446, 7.7067, 3.3228, 4.5735, 0.9725, 4.4612, 5.5659, 1.8319,
         0.4702],
        [2.3754, 4.6869, 5.7110, 0.3940, 0.6123, 0.9728, 0.3609, 0.8931, 0.2544,
         0.3075],
        [5.2636, 3.2369, 2.5078, 4.1443, 0.8700, 0.3737, 0.0480, 1.3275, 1.1162,
         0.2311],
        [5.3961, 3.9986, 5.9879, 6.5103, 6.3827, 3.5567, 3.3901, 0.8353, 1.7562,
         1.4004],
        [1.6903, 2.7308, 3.0309, 7.3685, 5.6949, 4.1521, 0.2019, 0.1429, 0.9643,
         0.2103],
        [6.8832, 2.2706, 7.2402, 0.1701, 8.5359, 3.3755, 1.1014, 4.8128, 5.6926,
         1.1468]])

### 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [8]:
d = torch.matmul(c, c.T)
print(d.shape)
d

torch.Size([6, 6])


tensor([[193.0948,  74.4797,  84.3895, 162.5095,  94.1824, 189.1199],
        [ 74.4797,  62.7893,  46.0830,  78.5359,  45.0634,  83.4163],
        [ 84.3895,  46.0830,  65.6071,  93.7798,  63.7048,  84.1913],
        [162.5095,  78.5359,  93.7798, 193.9689, 140.0680, 176.5279],
        [ 94.1824,  45.0634,  63.7048, 140.0680, 124.5027, 110.3005],
        [189.1199,  83.4163,  84.1913, 176.5279, 110.3005, 247.3374]])

### 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [9]:
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)

y = x**3 + z - 75*t

In [10]:
y.backward()

In [11]:
print(f"dy/dx(1, 0.5, 2) = {x.grad}")
print(f"dy/dz(1, 0.5, 2) = {z.grad}")
print(f"dy/dt(1, 0.5, 2) = {t.grad}")

dy/dx(1, 0.5, 2) = 3.0
dy/dz(1, 0.5, 2) = 1.0
dy/dt(1, 0.5, 2) = -75.0


### 8. Создайте единичный тензор размера 5x6

In [12]:
e = torch.ones(5,6,)
print(e.shape)
e

torch.Size([5, 6])


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

### 9. Переведите его в формат numpy

In [13]:
e = e.numpy()
print(e.shape)
e

(5, 6)


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

---